export const PANEL_PLACEHOLDERS = Object.freeze({
  'panel.operation.attempts': ['count'], 'panel.reconciliation.complete': ['count'], 'panel.reconciliation.issues': ['count'],
  'panel.queue.confirm.delete': ['title', 'count'], 'panel.queue.clear.confirm': ['title', 'count', 'refunds'],
  'panel.queue.clear.changed': ['count'], 'panel.queue.clear.done': ['count', 'refunds'],
  'panel.widget.card_details': ['queue', 'width', 'height', 'id'],
  'panel.command.audience.proposed': ['roles'], 'panel.command.audience.everyone_includes': ['roles'],
  'panel.entry.call.remaining': ['time'],
  'panel.queue_settings.call_message_default': ['user'],
  'panel.queue_settings.call_placeholders': ['user', 'queue', 'position', 'uid', 'account'],
  'panel.error.reference': ['id'],
  'panel.reward.candidate_counts': ['compatible', 'total'],
  'panel.reward.mismatch_summary': ['reasons'],
  'panel.reward.mismatch.title': ['count'],
  'panel.reward.mismatch.cost': ['count'],
  'panel.reward.mismatch.prompt': ['count'],
  'panel.reward.mismatch.uid': ['count'],
  'panel.reward.mismatch.stream_limit': ['count'],
  'panel.reward.mismatch.viewer_limit': ['count'],
  'panel.reward.mismatch.cooldown': ['count'],
  'panel.reward.mismatch.auto_fulfill': ['count'],
  'panel.reward.mismatch.skip_queue': ['count'],
  'panel.reward.mismatch.disabled': ['count'],
  'panel.reward.mismatch.not_paused': ['count'],
});
